### ISSUE TITLE
Getaddrinfo failed upon logging in

### ISSUE THREAD

**Issue by Ash195** [fortinet-solutions-cse/fortiosapi#44]
I am connected directly to a FortiGate 100E to test my code and upon logging in, I received a "getaddrinfo" failed error:

> Traceback (most recent call last):
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 316, in connect
    conn = self._new_conn()
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000271E236AC50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //192.168.1.159/logincheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000271E236AC50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "C:\Users\ktrang\Downloads\fortiosapi-master\fortiosapi-master\__init__.py", line 1, in <module>
    from fortiosapi.fortiosapi import FortiOSAPI
  File "C:\Users\ktrang\Downloads\fortiosapi-master\fortiosapi-master\fortiosapi\__init__.py", line 4, in <module>
    print(server.login(host = "https://192.168.1.159", username = "admin", password = "admin"))
  File "C:\Users\ktrang\Downloads\fortiosapi-master\fortiosapi-master\fortiosapi\fortiosapi.py", line 183, in login
    data='username=' + urllib.parse.quote(username) + '&secretkey=' + urllib.parse.quote(password) + "&ajax=1", timeout=self.timeout)
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ktrang\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //192.168.1.159/logincheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000271E236AC50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by thomnico** [comment]
This seems to show that your Fortigate is not reachable.
Can you https to it ? Is it properly licensed ? (if not use http)
